name: Master

on: 
   push:
     branches : 
       - master
   pull_request:
     branches : 
       - master

jobs:
  MacOS:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: use Setup-Scheme
      uses: guenchi/setup-scheme@master
      with:
        implementation: chez
    - run: scheme --version

  Linux:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: use Setup-Scheme
      uses: guenchi/setup-scheme@master
      with:
        implementation: chez

    - run: scheme --version


