name: Master

on: 
   push:
     branches : 
       - master
   pull_request:
     branches : 
       - master

jobs:
  MacOS:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
    - name: name
      run: echo "hello world"
